#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading installation settings..." --weight=3

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get --app=$app --key=domain)
path_url=$(ynh_app_setting_get --app=$app --key=path)
final_path=$(ynh_app_setting_get --app=$app --key=final_path) || ynh_die "This path already contains a folder"
phpversion=$(ynh_app_setting_get --app=$app --key=phpversion)

#=================================================
# CHECK VERSION
#=================================================

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
#=================================================
ynh_script_progression --message="Backing up Garradin before upgrading (may take a while)..." --weight=30

# Backup the current version of the app
ynh_backup_before_upgrade
ynh_clean_setup () {
	# restore it if the upgrade fails
	ynh_restore_upgradebackup
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression --message="Ensuring downward compatibility..." --weight=1

# If final_path doesn't exist, create it
if [ -z "$final_path" ]; then
  final_path=/var/www/$app
  ynh_app_setting_set --app=$app --key=final_path --value=$final_path
fi

### If nobody installed your app before 3.7,
### then you may safely remove these lines

# Cleaning legacy permissions
# is_public=$(ynh_app_setting_get --app=$app --key=is_public)

if [ -n "$is_public" ]; then
  # Remove protected_uris
  ynh_app_setting_delete --app=$app --key=protected_uris

  #Removing skipped/unprotected_uris under certain conditions, remove the visitors group added during the migration process of 3.7
  #Remove skipped_uris. If the app was public, add visitors again to the main permission
  if ynh_permission_has_user --permission=main --user=visitors
  then
    ynh_app_setting_delete --app=$app --key=skipped_uris
    ynh_permission_update --permission "main" --add "visitors"
  else
    ynh_app_setting_delete --app=$app --key=skipped_uris
  fi
  ynh_app_setting_delete --app=$app --key=is_public
fi

#=================================================
# Backup Data
#=================================================
ynh_script_progression --message="Backing up the data before upgrading (may take a while)..." --weight=30

bdd=$final_path/association.sqlite
squelettes=$final_path/www/squelettes

if  [ -d "$squelettes" ]; then
  cp -ar $squelettes /tmp/squelettes
fi

if [ -e "$bdd" ]; then
  cp -a $bdd /tmp/association.sqlite
fi

#=================================================
# CREATE DEDICATED USER
#=================================================
ynh_script_progression --message="Making sure dedicated system user exists..." --weight=1

# Create a dedicated user (if not existing)
ynh_system_user_create --username=$app --home_dir="$final_path"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Upgrading NGINX web server configuration..." --weight=2

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Upgrading PHP-FPM configuration..." --weight=2

# Create a dedicated PHP-FPM config
ynh_add_fpm_config --package="$extra_php_dependencies"

#=======================================================
# backup bdd, squelettes directory and add configuration
#=======================================================
ynh_script_progression --message="restore data..." --weight=10

backup_bdd=/tmp/association.sqlite
backup_squelettes=/tmp/squelettes

if 	[ -d "$backup_squelettes" ]
then
  cp -ar $backup_squelettes $final_path/www/squelettes
  ynh_secure_remove  $backup_squelettes
fi

if [ -e "$backup_bdd" ]
then
  cp -a $backup_bdd $final_path/association.sqlite
  ynh_secure_remove $backup_bdd
fi

key=$(ynh_string_random --length=50)
cp -a $final_path/config.dist.php $final_path/config.local.php
ynh_replace_string --match_string="const SECRET_KEY = '3xUhIgGwuovRKOjVsVPQ5yUMfXUSIOX2GKzcebsz5OINrYC50r';" --replace_string="const SECRET_KEY = '$key';" --target_file="$final_path/config.local.php"
if [ "$path_url" == "/" ]; then
ynh_replace_string --match_string="//const WWW_URI = '/asso/';" --replace_string="const WWW_URI = '$path_url';" --target_file="$final_path/config.local.php"
else
ynh_replace_string --match_string="//const WWW_URI = '/asso/';" --replace_string="const WWW_URI = '$path_url/';" --target_file="$final_path/config.local.php"
fi

# Permissions on files and directories
chmod -R o-rwx "$final_path"
chown -R $app:www-data "$final_path"
find "$final_path" -type d -exec chmod 550 {} +
find "$final_path" -type f -exec chmod 440 {} +
chmod 660 "$final_path/config.local.php"

#=================================================
# SETUP SSOWAT
#=================================================
ynh_script_progression --message="Upgrading permissions configuration..." --weight=2

# Create the visitors permission if needed
if ! ynh_permission_exists --permission "visitors"; then
  ynh_permission_create --permission "visitors"
fi

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression --message="Reloading NGINX web server..." --weight=1

ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# Finalise Upgrade
#=================================================
ynh_script_progression --message="Finalise upgrade" --weight=1

ynh_local_curl "/admin/index.php"
chmod 440 "$final_path/config.local.php"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of Garradin completed" --last
